version: 0.2
env:
  variables:
    TF_VERSION: 0.14.10


phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/workspaces/$WORKSPACE_NAME"
      - terraform init -input=false -backend-config=backend.hcl
      - terraform plan -input=false -out=${CODEBUILD_RESOLVED_SOURCE_VERSION}.tfplan

  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*.tfplan'